In [1]:
# importing the module
import numpy as np

In [2]:
array = np.array([1,2,3])  #create a one dimensional NumPy array 
print(array) #print the array

[1 2 3]


In [3]:
array2 = np.array([2,4,6,8,10,12,14,16,18,20,22,24])
print(array2.shape) #print the shape of array


(12,)


In [4]:
a = array2.reshape(3,4) #change the shape of a NumPy array 
print(a)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [5]:
print("Shape:",a.shape) #get the hape of an array
print("Dimension: ",a.ndim) #get the dimensions of a matrix
print("Data type: ",a.dtype.name) #find the data type of an array
print("Size: ",a.size) #find the size of an array
print("Type: ",type(a)) #find the type of an array

Shape: (3, 4)
Dimension:  2
Data type:  int32
Size:  12
Type:  <class 'numpy.ndarray'>


In [6]:
array3 = np.array([[2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]]) #create a two dimensional NumPy array 
print(array3)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [7]:
print(array3.shape) #print the shape of 2D array

(4, 4)


In [8]:
zeros= np.zeros((3,5)) #make a matrix of zeros 

In [9]:
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
zeros[1,2]=5 #change an element of a 2d array at any index
print(zeros) 

[[0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
ones = np.ones((2,4)) #create a matrix with all ones
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
np.empty((4,5)) #create an empty array

array([[4.67296746e-307, 1.69121096e-306, 1.89143331e-307,
        7.56599807e-307, 8.90104239e-307],
       [1.24610383e-306, 1.69118108e-306, 8.06632139e-308,
        1.20160711e-306, 1.69119330e-306],
       [1.29062229e-306, 1.60217812e-306, 1.37961370e-306,
        1.42417629e-306, 1.37961913e-306],
       [1.42418172e-306, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307]])

In [13]:
np.arange(10,50,5) #give a range to create a matrix; increase the numbers from 10 to 50 by 5s 


array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
a = np.linspace(0,10,20) #prints 20 numbers between 0 and 10
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [15]:
#Numerical operations on arrays
a = np.array([1,2,3])
b = np.array([4,5,6]) 

print(a+b) #compute the addition of two array.
print(a-b) #compute the subtraction of two array.
print(a**2) #calculate the square of an array

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [16]:
#Difference between List and Array
list1 = [1,2,3,4]

array = np.array([5,6,7,8])
#array tanımlamak için array'in içine liste yazılır.
print(list1)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [29]:
a = np.array([1,2,3])

In [18]:
b=a
c=a

In [19]:
b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [31]:
a[0]=5

In [30]:
d = a.copy()
print(d)

[1 2 3]


In [32]:
d

array([1, 2, 3])

In [33]:
a= np.array([1,2,3,4,5,6,7]) 
print(a) #print the array

[1 2 3 4 5 6 7]


In [34]:
a[0] #print the first index of an array

1

In [35]:
a[0:4] #print the certain range of an array

array([1, 2, 3, 4])

In [36]:
a[::-1] #reverse the array

array([7, 6, 5, 4, 3, 2, 1])

In [46]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #create 2D array
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
print(b[1,1]) #print the certain index of 2D array

[1, 1]


In [39]:
print(b[:,1])

[2 7]


In [40]:
b[1,:]

array([ 6,  7,  8,  9, 10])

In [41]:
b[1,1:4]

array([7, 8, 9])

In [42]:
b[-1,:]

array([ 6,  7,  8,  9, 10])

In [43]:
b[:,-1]

array([ 5, 10])

In [45]:
b = b.ravel() #convert 2D array to 1D array
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [47]:
b.T #transpose of a matrix

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])